# This file contains values from Cookiecutter

default_context:
  project_name: "imagetree"
  project_description: "ImageTree is an image processing library that uses quadtrees to simplify working with very large files."
  organization: "Josh Borrow"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "jborrow"
  email: "josh@joshborrow.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
